export const GET_ALL_DATA = 'GET_ALL_DATA';
export const GET_ALL_DATA_SUCCEEDED = 'GET_ALL_DATA_SUCCEEDED';
export const GET_ALL_DATA_FAILED = 'GET_ALL_DATA_FAILED';
export const GET_DETAIL_DATA = 'GET_DETAIL_DATA';
export const TOGGLE_STATS = 'TOGGLE_STATS';
