// Add Content
export const ADD_TITLE = 'ADD_TITLE';
export const ADD_TITLE_SUCCEEDED = 'ADD_TITLE_SUCCEEDED';
export const ADD_TITLE_FAILED = 'ADD_TITLE_FAILED';

// Get All Data
export const GET_ALL_DATA = 'GET_ALL_DATA';
export const GET_ALL_DATA_SUCCEEDED = 'GET_ALL_DATA_SUCCEEDED';
export const GET_ALL_DATA_FAILED = 'GET_ALL_DATA_FAILED';

// Add As Favorite
export const ADD_AS_FAVORITE = 'ADD_AS_FAVORITE';
export const ADD_AS_FAVORITE_SUCCEEDED = 'ADD_AS_FAVORITE_SUCCEEDED';
export const ADD_AS_FAVORITE_FAILED = 'ADD_AS_FAVORITE_FAILED';

// Remove As Favorite
export const REMOVE_AS_FAVORITE = 'REMOVE_AS_FAVORITE';
export const REMOVE_AS_FAVORITE_SUCCEEDED = 'REMOVE_AS_FAVORITE_SUCCEEDED';
export const REMOVE_AS_FAVORITE_FAILED = 'REMOVE_AS_FAVORITE_FAILED';

// Sync Actions
export const GET_DETAIL_DATA = 'GET_DETAIL_DATA';
export const TOGGLE_STATS = 'TOGGLE_STATS';
